// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: greentoken.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnergyEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs int64                  `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	AgentId     string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname    string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Pid         int32                  `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	Workload    string                 `protobuf:"bytes,5,opt,name=workload,proto3" json:"workload,omitempty"` // ex: "vllm", "llama.cpp", "ollama"
	Model       string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`       // ex: "llama3-70b"
	// Energia na janela de medição
	WattsCpu  float64 `protobuf:"fixed64,7,opt,name=watts_cpu,json=wattsCpu,proto3" json:"watts_cpu,omitempty"`
	WattsDram float64 `protobuf:"fixed64,8,opt,name=watts_dram,json=wattsDram,proto3" json:"watts_dram,omitempty"`
	WattsGpu  float64 `protobuf:"fixed64,9,opt,name=watts_gpu,json=wattsGpu,proto3" json:"watts_gpu,omitempty"`
	GpuIndex  int32   `protobuf:"varint,10,opt,name=gpu_index,json=gpuIndex,proto3" json:"gpu_index,omitempty"` // -1 se sem GPU
	// Throughput na mesma janela
	TokensInWindow int64   `protobuf:"varint,11,opt,name=tokens_in_window,json=tokensInWindow,proto3" json:"tokens_in_window,omitempty"`
	WindowSeconds  float64 `protobuf:"fixed64,12,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
	// Utilização (para contexto, não para atuar)
	CpuUtilPct    float64 `protobuf:"fixed64,13,opt,name=cpu_util_pct,json=cpuUtilPct,proto3" json:"cpu_util_pct,omitempty"`
	GpuUtilPct    float64 `protobuf:"fixed64,14,opt,name=gpu_util_pct,json=gpuUtilPct,proto3" json:"gpu_util_pct,omitempty"`
	GpuMemUsed    uint64  `protobuf:"varint,15,opt,name=gpu_mem_used,json=gpuMemUsed,proto3" json:"gpu_mem_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnergyEvent) Reset() {
	*x = EnergyEvent{}
	mi := &file_greentoken_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnergyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnergyEvent) ProtoMessage() {}

func (x *EnergyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_greentoken_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnergyEvent.ProtoReflect.Descriptor instead.
func (*EnergyEvent) Descriptor() ([]byte, []int) {
	return file_greentoken_proto_rawDescGZIP(), []int{0}
}

func (x *EnergyEvent) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *EnergyEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EnergyEvent) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnergyEvent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *EnergyEvent) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

func (x *EnergyEvent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EnergyEvent) GetWattsCpu() float64 {
	if x != nil {
		return x.WattsCpu
	}
	return 0
}

func (x *EnergyEvent) GetWattsDram() float64 {
	if x != nil {
		return x.WattsDram
	}
	return 0
}

func (x *EnergyEvent) GetWattsGpu() float64 {
	if x != nil {
		return x.WattsGpu
	}
	return 0
}

func (x *EnergyEvent) GetGpuIndex() int32 {
	if x != nil {
		return x.GpuIndex
	}
	return 0
}

func (x *EnergyEvent) GetTokensInWindow() int64 {
	if x != nil {
		return x.TokensInWindow
	}
	return 0
}

func (x *EnergyEvent) GetWindowSeconds() float64 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

func (x *EnergyEvent) GetCpuUtilPct() float64 {
	if x != nil {
		return x.CpuUtilPct
	}
	return 0
}

func (x *EnergyEvent) GetGpuUtilPct() float64 {
	if x != nil {
		return x.GpuUtilPct
	}
	return 0
}

func (x *EnergyEvent) GetGpuMemUsed() uint64 {
	if x != nil {
		return x.GpuMemUsed
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_greentoken_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_greentoken_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_greentoken_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_greentoken_proto protoreflect.FileDescriptor

const file_greentoken_proto_rawDesc = "" +
	"\n" +
	"\x10greentoken.proto\x12\n" +
	"greentoken\"\xd8\x03\n" +
	"\vEnergyEvent\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x03R\vtimestampNs\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x05R\x03pid\x12\x1a\n" +
	"\bworkload\x18\x05 \x01(\tR\bworkload\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x12\x1b\n" +
	"\twatts_cpu\x18\a \x01(\x01R\bwattsCpu\x12\x1d\n" +
	"\n" +
	"watts_dram\x18\b \x01(\x01R\twattsDram\x12\x1b\n" +
	"\twatts_gpu\x18\t \x01(\x01R\bwattsGpu\x12\x1b\n" +
	"\tgpu_index\x18\n" +
	" \x01(\x05R\bgpuIndex\x12(\n" +
	"\x10tokens_in_window\x18\v \x01(\x03R\x0etokensInWindow\x12%\n" +
	"\x0ewindow_seconds\x18\f \x01(\x01R\rwindowSeconds\x12 \n" +
	"\fcpu_util_pct\x18\r \x01(\x01R\n" +
	"cpuUtilPct\x12 \n" +
	"\fgpu_util_pct\x18\x0e \x01(\x01R\n" +
	"gpuUtilPct\x12 \n" +
	"\fgpu_mem_used\x18\x0f \x01(\x04R\n" +
	"gpuMemUsed\"/\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2S\n" +
	"\x13GreenTokenCollector\x12<\n" +
	"\fStreamEnergy\x12\x17.greentoken.EnergyEvent\x1a\x0f.greentoken.Ack(\x010\x01B\x12Z\x10greentoken/pb;pbb\x06proto3"

var (
	file_greentoken_proto_rawDescOnce sync.Once
	file_greentoken_proto_rawDescData []byte
)

func file_greentoken_proto_rawDescGZIP() []byte {
	file_greentoken_proto_rawDescOnce.Do(func() {
		file_greentoken_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_greentoken_proto_rawDesc), len(file_greentoken_proto_rawDesc)))
	})
	return file_greentoken_proto_rawDescData
}

var file_greentoken_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_greentoken_proto_goTypes = []any{
	(*EnergyEvent)(nil), // 0: greentoken.EnergyEvent
	(*Ack)(nil),         // 1: greentoken.Ack
}
var file_greentoken_proto_depIdxs = []int32{
	0, // 0: greentoken.GreenTokenCollector.StreamEnergy:input_type -> greentoken.EnergyEvent
	1, // 1: greentoken.GreenTokenCollector.StreamEnergy:output_type -> greentoken.Ack
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_greentoken_proto_init() }
func file_greentoken_proto_init() {
	if File_greentoken_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_greentoken_proto_rawDesc), len(file_greentoken_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_greentoken_proto_goTypes,
		DependencyIndexes: file_greentoken_proto_depIdxs,
		MessageInfos:      file_greentoken_proto_msgTypes,
	}.Build()
	File_greentoken_proto = out.File
	file_greentoken_proto_goTypes = nil
	file_greentoken_proto_depIdxs = nil
}
