// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.2
// source: greentoken.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GreenTokenCollector_StreamEnergy_FullMethodName = "/greentoken.GreenTokenCollector/StreamEnergy"
)

// GreenTokenCollectorClient is the client API for GreenTokenCollector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreenTokenCollectorClient interface {
	StreamEnergy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EnergyEvent, Ack], error)
}

type greenTokenCollectorClient struct {
	cc grpc.ClientConnInterface
}

func NewGreenTokenCollectorClient(cc grpc.ClientConnInterface) GreenTokenCollectorClient {
	return &greenTokenCollectorClient{cc}
}

func (c *greenTokenCollectorClient) StreamEnergy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EnergyEvent, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GreenTokenCollector_ServiceDesc.Streams[0], GreenTokenCollector_StreamEnergy_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EnergyEvent, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GreenTokenCollector_StreamEnergyClient = grpc.BidiStreamingClient[EnergyEvent, Ack]

// GreenTokenCollectorServer is the server API for GreenTokenCollector service.
// All implementations must embed UnimplementedGreenTokenCollectorServer
// for forward compatibility.
type GreenTokenCollectorServer interface {
	StreamEnergy(grpc.BidiStreamingServer[EnergyEvent, Ack]) error
	mustEmbedUnimplementedGreenTokenCollectorServer()
}

// UnimplementedGreenTokenCollectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGreenTokenCollectorServer struct{}

func (UnimplementedGreenTokenCollectorServer) StreamEnergy(grpc.BidiStreamingServer[EnergyEvent, Ack]) error {
	return status.Error(codes.Unimplemented, "method StreamEnergy not implemented")
}
func (UnimplementedGreenTokenCollectorServer) mustEmbedUnimplementedGreenTokenCollectorServer() {}
func (UnimplementedGreenTokenCollectorServer) testEmbeddedByValue()                             {}

// UnsafeGreenTokenCollectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreenTokenCollectorServer will
// result in compilation errors.
type UnsafeGreenTokenCollectorServer interface {
	mustEmbedUnimplementedGreenTokenCollectorServer()
}

func RegisterGreenTokenCollectorServer(s grpc.ServiceRegistrar, srv GreenTokenCollectorServer) {
	// If the following call panics, it indicates UnimplementedGreenTokenCollectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GreenTokenCollector_ServiceDesc, srv)
}

func _GreenTokenCollector_StreamEnergy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreenTokenCollectorServer).StreamEnergy(&grpc.GenericServerStream[EnergyEvent, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GreenTokenCollector_StreamEnergyServer = grpc.BidiStreamingServer[EnergyEvent, Ack]

// GreenTokenCollector_ServiceDesc is the grpc.ServiceDesc for GreenTokenCollector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreenTokenCollector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greentoken.GreenTokenCollector",
	HandlerType: (*GreenTokenCollectorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEnergy",
			Handler:       _GreenTokenCollector_StreamEnergy_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "greentoken.proto",
}
